version: "3.7"

services:
  backend:
    build:
      context: "./backend"
      target: dev
    environment:
      - PORT=${PORT}
      - CORS_ORIGIN=${CORS_ORIGIN}
      - JWT_SECRET=${JWT_SECRET}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    command: bun run dev

  frontend:
    build:
      context: "./frontend"
      target: dev
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_URL=${VITE_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
