version: "3.7"

services:
  backend:
    build:
      context: "./backend"
    environment:
      - SERVER_PORT=${SERVER_PORT}
      - VITE_API_URL=${VITE_API_URL}
      - VITE_URL=${VITE_URL}
      - FRONTEND_URL=${VITE_URL}
    volumes:
      - ./backend:/app
      - /app/node_modules
    ports:
      - 5000:${SERVER_PORT}
    command: npm run dev

  frontend:
    build:
      context: "./frontend"
    environment:
      - VITE_API_URL=${VITE_API_URL}
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev
