name: ghcr
on:
  push:
    tags:
      - "v*.*.*"
permissions:
  contents: read
  packages: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - uses: docker/build-push-action@v6
        with:
          context: ./backend
          target: prod
          push: true
          tags: |
            ghcr.io/mescoczubinski/meetly-backend:${{ github.ref_name }}
      - uses: docker/build-push-action@v6
        with:
          context: ./frontend
          target: prod
          push: true
          build-args: |
            VITE_API_URL=${{ vars.VITE_API_URL }}
            VITE_URL=${{ vars.VITE_URL }}
          tags: |
            ghcr.io/mescoczubinski/meetly-frontend:${{ github.ref_name }}
